# Generated by Django 5.2.17 on 2026-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='matiere',
            field=models.CharField(choices=[('FRANCAIS', 'Francais'), ('ANGLAIS', 'Anglais'), ('HISTOIRE_GEOGRAPHIE', 'Histoire-geographie'), ('MATHEMATIQUE', 'Mathematique'), ('EPS', 'EPS'), ('PHYSIQUE_CHIMIE', 'Physique-Chimie'), ('ALLEMAND', 'Allemand')], max_length=150),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('GS', 'Grande Section'), ('MS', 'Moyenne Section'), ('PS', 'Petite Section'), ('6EME', '6eme'), ('5EME', '5eme'), ('4EME', '4eme'), ('3EME', '3eme'), ('2NDEC', '2ndeC'), ('1ERED', '1ereD'), ('TLED', 'TleD')], max_length=150),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom', 'matiere'), name='classe_niveau_matiere_unique'),
        ),
    ]
