# Generated by Django 5.2.17 on 2026-09-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_alter_classe_matiere_alter_classe_nom_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classe',
            name='classe_niveau_matiere_unique',
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom', 'enseignant'), name='classe_enseignant_unique'),
        ),
    ]
